### ISSUE TITLE
When invoked with babel-loader, fails

### ISSUE THREAD

**Issue by bilbosan** [snowyu/inherits-ex.js#2]
In isEmptyFunction.js:

```
module.exports = function(aFunc, istanbul) {
    if (!istanbul) try {istanbul = require('istanbul');} catch(e){}
};
```

Webpack / Browserify / etc don't do "conditional" requires, so that `try` block doesn't do what you think it does. The require gets executed at build time, and if you do not happen to have istanbul installed, you get warnings like this:

```
Module not found: Error: Can't resolve 'istanbul' in '/Users/patrickminton/src/exm-admin-tool/node_modules/inherits-ex/lib'
 @ ./~/inherits-ex/lib/isEmptyFunction.js 5:35-54
 @ ./~/inherits-ex/lib/newPrototype.js
 @ ./~/inherits-ex/lib/inheritsDirectly.js
 @ ./~/inherits-ex/index.js
```

Worse, if you DO have istanbul installed, it breaks the build, because Istanbul itself does something that does not work in browsers, in https://github.com/gotwarlost/istanbul/blob/master/lib/hook.js:

```
var path = require('path'),
    fs = require('fs'),
    Module = require('module'),
```

`require('module') works fine in node.js, but does not work in a browser:

```
→ node
> const m = require('module')
undefined
> m
{ [Function: Module]
```

which is probably fine, because you aren't supposed to use istanbul in a browser....except that isEmptyFunction will try to do just that. The result is builds that break:

```
ERROR in ./~/istanbul/lib/hook.js
Module not found: Error: Can't resolve 'module' in '/Users/patrickminton/src/exm-admin-tool/node_modules/istanbul/lib'
 @ ./~/istanbul/lib/hook.js 36:13-30
 @ ./~/istanbul/index.js
 @ ./~/inherits-ex/lib/isEmptyFunction.js
 @ ./~/inherits-ex/lib/newPrototype.js
 @ ./~/inherits-ex/lib/inheritsDirectly.js
 @ ./~/inherits-ex/index.js
```

**Comment by snowyu** [comment]
This is used only to avoid glicth after the istanbul(code coverage) injected codes to the function.

**Comment by bilbosan** [comment]
I'm not sure WHY you did it is important at all. The fact is still that if someone includes your package and Istanbul in their project, and then uses webpack2 to build, they're going to get a broken build, because `try() { require() }` does not catch the errors like you think it does.

In my case, the offending module that decided to include your module is `mime-types`, which includes `path`, which uses this.

**Comment by snowyu** [comment]
It could get in trouble if you using `isEmpty` function and istanbul on your project.

btw this fixes : `eval('requre("")')` can not work?

**Comment by snowyu** [comment]
I do not know whether all webpack/browserify/... follow this rule: https://github.com/defunctzombie/package-browser-field-spec
